export const items =  [
    {
      id: 1,
      category: 'Chocolate Cream',
      title: "Chocolate Cream ",
      imgSrc: 'Dataimg/chocolate-cream-cake-half-kg_1.webp',
      amazonLink: 'https://hunnybuns.vercel.app/ ',
      description: 'Chocolate premix, Refined oil, Breakfast Sugar, Whip topping cream',
      price: '240',
    },
    {
        id: 2,
        category: 'Chocolate Cream',
        title: "Chocolate Cream",
        imgSrc: 'Dataimg/chocolate-fruit-gateau-2kg-eggless_23.webp',
        amazonLink: 'https://hunnybuns.vercel.app/ ',
        description: 'Chocolate premix, Refined oil, Breakfast Sugar, Whip topping cream',
        price: '300',
      },
      {
        id: 3,
        category: 'Chocolate Cream',
        title: "Chocolate Cream ",
        imgSrc: 'Dataimg/chocolate-cream-cake-half-kg_1.webp',
        amazonLink: 'https://hunnybuns.vercel.app/ ',
        description: 'Chocolate premix, Refined oil, Breakfast Sugar, Whip topping cream',
        price: '240',
      },
    {
      id: 4,
      category: 'Black Forest',
      title: "Black Forest",
      imgSrc: 'Dataimg/black-forest-cake-half-kg-eggless_3.webp',
      amazonLink: 'https://hunnybuns.vercel.app/',
      description: 'Chocolate premix, Refined oil, Breakfast Sugar, Whip topping cream',
      price: '300',
    },
    {
      id: 5,
      category: 'Black Forest',
      title: "Black Forest",
      imgSrc: 'Dataimg/black-forest-cake-half-kg-eggless_3.webp',
      amazonLink: 'https://hunnybuns.vercel.app/',
      description: 'Chocolate premix, Refined oil, Breakfast Sugar, Whip topping cream',
      price: '299',
    },
    {
      id: 6,
      category: 'Red Velvet',
      title: "Red Velvet",
      imgSrc: 'Dataimg/red-velvet-bento-cake_7.webp',
      amazonLink: 'https://hunnybuns.vercel.app/',
      description: 'Chocolate premix, Refined oil, Breakfast Sugar, Whip topping cream',
      price: '799',
    },
    {
      id: 7,
      category: 'Red Velvet',
      title: "Red Velvet",
      imgSrc: 'Dataimg/red-velvet-fresh-cream-cake-half-kg-eggless_5.webp',
      amazonLink: 'https://hunnybuns.vercel.app/',
      description: 'Chocolate premix, Refined oil, Breakfast Sugar, Whip topping cream',
      price: '199',
    },
    {
      id: 8,
      category: 'Red Velvet',
      title: "Red Velvet",
      imgSrc: 'Dataimg/red-velvet-fresh-cream-cake-half-kg-eggless_5.webp',
      amazonLink: 'https://hunnybuns.vercel.app/',
      description: 'Chocolate premix, Refined oil, Breakfast Sugar, Whip topping cream',
      price: '699',
    },
    {
      id: 9,
      category: 'Vanilla Cream Cake',
      title: "Vanilla Cream Cake",
      imgSrc: 'Dataimg/mango-magic-cream-cake_22.webp',
      amazonLink: 'https://hunnybuns.vercel.app/',
      description: 'Chocolate premix, Refined oil, Breakfast Sugar, Whip topping cream',
      price: '299',
    },
    {
      id: 10,
      category: 'Vanilla Cream Cake',
      title: "Vanilla Cream Cake",
      imgSrc: 'Dataimg/pineapple-cake-half-kg-eggless_14.webp',
      amazonLink: 'https://hunnybuns.vercel.app/',
      description: 'Chocolate premix, Refined oil, Breakfast Sugar, Whip topping cream',
      price: '499',
    },
    {
      id: 11,
      category: 'Vanilla Cream Cake',
      title: "Vanilla Cream Cake",
      imgSrc: 'Dataimg/delicious-pineapple-cream-cake-eggless-half-kg_17.webp',
      amazonLink: 'https://hunnybuns.vercel.app/',
      description: 'Chocolate premix, Refined oil, Breakfast Sugar, Whip topping cream',
      price: '899',
    },


    {
        id: 12,
        category: 'Vanilla Cream Cake',
        title: "Vanilla Cream Cake",
        imgSrc: 'Dataimg/delicious-pineapple-cake-half-kg-eggless_16.webp',
        amazonLink: 'https://hunnybuns.vercel.app/',
        description: 'Chocolate premix, Refined oil, Breakfast Sugar, Whip topping cream',
        price: '899',
      },
      {
        id: 13,
        category: ' Butterscotch Cakes',
        title: "Butterscotch Cakes",
        imgSrc: 'Dataimg/butterscotch-cake-half-kg_8.webp ',
        amazonLink: 'https://hunnybuns.vercel.app/',
        description: 'Chocolate premix, Refined oil, Breakfast Sugar, Whip topping cream',
        price: '499',
      },
      {
        id: 14,
        category: 'Butterscotch Cakes',
        title: "Butterscotch Cakes",
        imgSrc: 'Dataimg/butterscotch-cream-cake-half-kg_10.webp',
        amazonLink: 'https://hunnybuns.vercel.app/',
        description: 'Chocolate premix, Refined oil, Breakfast Sugar, Whip topping cream',
        price: '299',
      },
      {
        id: 15,
        category: 'Butterscotch Cakes',
        title: "Butterscotch Cakes",
        imgSrc: 'Dataimg/butterscotch-cream-cake-half-kg_10.webp',
        amazonLink: 'https://hunnybuns.vercel.app/',
        description: 'Chocolate premix, Refined oil, Breakfast Sugar, Whip topping cream',
        price: '799',
      },
      {
        id: 16,
        category: '  Pineapple Cakes',
        title: "Pineapple Cakes",
        imgSrc: 'Dataimg/delicious-pineapple-cake-half-kg-eggless_16.webp ',
        amazonLink: 'https://hunnybuns.vercel.app/',
        description: 'Chocolate premix, Refined oil, Breakfast Sugar, Whip topping cream',
        price: '199',
      },
      {
        id: 17,
        category: 'Pineapple Cakes',
        title: "Pineapple Cakes",
        imgSrc: 'Dataimg/delicious-pineapple-cream-cake-eggless-half-kg_17.webp',
        amazonLink: 'https://hunnybuns.vercel.app/',
        description: 'Chocolate premix, Refined oil, Breakfast Sugar, Whip topping cream',
        price: '699',
      },
      {
        id: 18,
        category: 'Pineapple Cakes',
        title: "Pineapple Cakes",
        imgSrc: 'Dataimg/red-velvet-fresh-cream-cake-half-kg-eggless_5.webp',
        amazonLink: 'https://hunnybuns.vercel.app/',
        description: 'Chocolate premix, Refined oil, Breakfast Sugar, Whip topping cream',
        price: '299',
      },
      {
        id: 19,
        category: 'Truffle Cakes',
        title: "Truffle Cakes",
        imgSrc: 'Dataimg/truffle-walnut-cake-half-kg_12.webp ',
        amazonLink: 'https://hunnybuns.vercel.app/',
        description: 'Chocolate premix, Refined oil, Breakfast Sugar, Whip topping cream',
        price: '499',
      },
      {
        id: 20,
        category: 'Truffle Cakes',
        title: "Truffle Cakes",
        imgSrc: ' Dataimg/decorated-chocolate-truffle-cake-half-kg_11.webp',
        amazonLink: 'https://hunnybuns.vercel.app/',
        description: 'Chocolate premix, Refined oil, Breakfast Sugar, Whip topping cream',
        price: '899',
      },
      {
        id: 21,
        category: 'Truffle Cakes',
        title: "Truffle Cakes",
        imgSrc: 'Dataimg/paradise-designer-truffle-cake-1-kg_13.webp',
        amazonLink: 'https://hunnybuns.vercel.app/',
        description: 'Chocolate premix, Refined oil, Breakfast Sugar, Whip topping cream',
        price: '899',
      },
      {
        id: 22,
        category: 'Fruit Cakes',
        title: "Fruit Cakes",
        imgSrc: 'Dataimg/red-velvet-fresh-cream-cake-half-kg-eggless_5.webp ',
        amazonLink: 'https://hunnybuns.vercel.app/',
        description: 'Chocolate premix, Refined oil, Breakfast Sugar, Whip topping cream',
        price: '899',
      },
      {
        id: 23,
        category: 'Fruit Cakes',
        title: "Fruit Cakes",
        imgSrc: 'Dataimg/fruit-walnut-designer-cake-2-kg-eggless_18.webp ',
        amazonLink: 'https://hunnybuns.vercel.app/',
        description: 'Chocolate premix, Refined oil, Breakfast Sugar, Whip topping cream',
        price: '899',
      },
      {
        id: 24,
        category: 'Fruit Cakes',
        title: "Fruit Cakes",
        imgSrc: 'Dataimg/fruit-overload-cake-2-kg-eggless_19.webp',
        amazonLink: 'https://hunnybuns.vercel.app/',
        description: ' Chocolate premix, Refined oil, Breakfast Sugar, Whip topping cream ',
        price: '899',
      },
      {
        id: 25,
        category: 'Fruit Cakes',
        title: "Fruit Cakes",
        imgSrc: 'Dataimg/diwali-blissful-fruit-cake-1kg_20.webp',
        amazonLink: 'https://hunnybuns.vercel.app/',
        description: 'Chocolate premix, Refined oil, Breakfast Sugar, Whip topping cream',
        price: '899',
      },
      {
        id: 26,
        category: 'Vanilla Cream Cake',
        title: "Vanilla Cream Cake",
        imgSrc: 'Dataimg/valentine-s-heart-red-velvet-cake-half-kg_6.webp',
        amazonLink: 'https://hunnybuns.vercel.app/',
        description: ' Chocolate premix, Refined oil, Breakfast Sugar, Whip topping cream',
        price: '899',
      },
  ]